### ISSUE TITLE
Add/change border color of author tag to black

### ISSUE THREAD

**Issue by LorduFreeman** [mouse0270/module-credits#1]
First: Love this module, very small but super useful for heavy module-use. 

A minor quirk I noticed: The author tags have a coloured border while every other tag has a black border. I'd suggest it either gets changed to a black border as well or the module restyles every other border as well :)

**Comment by mouse0270** [comment]
Thank you very much, I've got about 100-150 modules and really needed a place to quickly access stuff. Thank you for the kind words.

As for the actual use... As a UI/UX designer... I hate that I missed that and I will have that fixed and out tomorrow morning. 

The worst thing about it is, I kinda hate the black border... but I also don't want to over step and recolor the borders of the other tags... I guess I gotta make a choice and stick to it in the morning.

**Comment by mouse0270** [comment]
The black border has been included for consistance with all of the other foundry tags in v0.0.2. Thanks for bringing it to my attention!
