### ISSUE TITLE
Console error in Foundry 9.245

### ISSUE THREAD

**Issue by Artemisthemp** [mouse0270/module-credits#10]
An error will appear in the console window a few second after a 5e world have been loaded on Foundry 9.245.
![Module manager error](https://user-images.githubusercontent.com/81526156/151718416-a1bea480-d6e2-4a59-836d-529dbe867e67.png)

**Comment by mouse0270** [comment]
This is an issue with a module and the author tag. Could you provide me a list of your modules installed?

**Comment by Artemisthemp** [comment]
Those are the modules, that I have installed.
[TidyUi list.txt](https://github.com/mouse0270/module-credits/files/7967017/TidyUi.list.txt)

**Comment by mouse0270** [comment]
Thats a big list, but I figured out the issue. It appears that one of those modules is using the `author` tag as either an array or an object. So my code breaks. I am pushing an update in a few minutes, if you don't mind I can ping you here and let you know the update is pushed and you can check it for me?

**Comment by mouse0270** [comment]
> An error will appear in the console window a few second after a 5e world have been loaded on Foundry 9.245. ![Module manager error](https://user-images.githubusercontent.com/81526156/151718416-a1bea480-d6e2-4a59-836d-529dbe867e67.png)

If you can, update to the latest version and let me know its not broken anymore so I can close this ticket.

**Comment by Artemisthemp** [comment]
No error thrown in the latest version, so the issue can be closed

**Comment by mouse0270** [comment]
Thanks for reporting, let me know if you come across any other issues
