### ISSUE TITLE
[Bug] After update to 2.2.0, the module is not marked as compatible with v11, but also controls in modules window are missing

### ISSUE THREAD

**Issue by r-valyar** [mouse0270/module-credits#101]
After update to 2.2.0, the module is still not marked as compatible with v11, but the main issue is that many of the controls available in the previous module next to each module (such as opening its Configuration windows, follow the URL to the project home etc.) are missing:

![image](https://github.com/mouse0270/module-credits/assets/63558984/39ee0475-93b0-4d3a-b54c-96cbe7660773)

**Comment by r-valyar** [comment]
I understand for the v11 :) I hope this is tested soon. When I open the Manage Module window this is what I see in the console:
```

Uncaught (in promise) TypeError: t.querySelector(...) is null
[Detected 2 packages: module-credits, lib-wrapper]
    renderModuleManagement bundle.min.mjs:1
    #call foundry.js:724
    callAll foundry.js:681
    _render foundry.js:5153
    _render foundry.js:5822
    render foundry.js:5067
    _onSettingsButton foundry.js:76701
    jQuery 9
    activateListeners foundry.js:76682
    _render foundry.js:5138
    _render foundry.js:60343
    _render foundry.js:60113
    render foundry.js:5067
    initializeUI foundry.js:8069
    setupGame foundry.js:7931
    _initializeGameView foundry.js:8999
    _initializeView foundry.js:8975
    initialize foundry.js:7825
    call_wrapped libWrapper-wrapper.js:507
    libWrapperInit libWrapper-api.js:803
    initialize#0 libWrapper-wrapper.js:187
    <anonymous> foundry.js:79693
    async* foundry.js:79675
bundle.min.mjs:1:91766
    renderModuleManagement bundle.min.mjs:1
    AsyncFunctionNext self-hosted:756
    (Async: async)
    #call foundry.js:724
    callAll foundry.js:681
    _render foundry.js:5153
    AsyncFunctionNext self-hosted:756
    (Async: async)
    _render foundry.js:5822
    render foundry.js:5067
    _onSettingsButton foundry.js:76701
    jQuery 9
    activateListeners foundry.js:76682
    _render foundry.js:5138
    AsyncFunctionNext self-hosted:756
    (Async: async)
    _render foundry.js:60343
    _render foundry.js:60113
    InterpretGeneratorResume self-hosted:1359
    AsyncFunctionNext self-hosted:756
    (Async: async)
    render foundry.js:5067
    initializeUI foundry.js:8069
    setupGame foundry.js:7931
    InterpretGeneratorResume self-hosted:1359
    AsyncFunctionNext self-hosted:756
    (Async: async)
    _initializeGameView foundry.js:8999
    _initializeView foundry.js:8975
    initialize foundry.js:7825
    InterpretGeneratorResume self-hosted:1359
    AsyncFunctionNext self-hosted:756
    (Async: async)
    call_wrapped libWrapper-wrapper.js:507
    libWrapperInit libWrapper-api.js:803
    InterpretGeneratorResume self-hosted:1359
    AsyncFunctionNext self-hosted:756
    (Async: async)
    initialize#0 libWrapper-wrapper.js:187
    <anonymous> foundry.js:79693
    InterpretGeneratorResume self-hosted:1359
    AsyncFunctionNext self-hosted:756
    (Async: async)
    <anonymous> foundry.js:79675

```

**Comment by mouse0270** [comment]
Can you test this in Chrome or Edge. It looks like you are using Firefox? I wonder if its a bug in Firefox as for right now, this is what the currently released version looks like to me on Edge

![image](https://github.com/mouse0270/module-credits/assets/564874/9b51da8c-57cb-4613-9d4e-b88094c30ca4)

**Comment by mouse0270** [comment]
I don't currently have firefox installed, but I can install it and test it out on firefox later tonight when I get home.

**Comment by mouse0270** [comment]
So I just installed a https://gitlab.com/fvtt-modiphius/foundryvtt-conan2d20 and created a blank world and then installed MM+ and still don't have this issue, can you send me a list of your active modules? I am lost and until I can replicate the issue

**Comment by r-valyar** [comment]
Below is the list. I haven't tried on clean world yet, but tomorrow when the session is over I can also help. 

### Active Modules
Bar Brawl v1.8.0 [Bugs URL](https://gitlab.com/woodentavern/foundryvtt-bar-brawl/-/issues)
Chat Portrait v0.8.46 [Bugs URL](https://github.com/p4535992/foundryvtt-chat-portrait/issues)
Combat Enhancements v1.2.2
Combat Tracker Effect Tooltips v3.0.0 [Bugs URL](https://github.com/dor-fvtt-released-modules/combat-tracker-effect-tooltips/issues)
Compendium Folders v2.5.7
Dice So Nice! v4.6.8 [Bugs URL](https://gitlab.com/riccisi/foundryvtt-dice-so-nice/-/issues)
Drag Anything to Hotbar v1.1.0
Drag Ruler v1.13.4 [Bugs URL](https://github.com/manuelVo/foundryvtt-drag-ruler/issues)
Filepicker Improvements v1.4.0 [Bugs URL](https://github.com/manuel-hegner/foundry-filepicker-favorites/issues)
FXMaster v3.6.0 [Bugs URL](https://github.com/ghost-fvtt/fxmaster/issues)
GM Screen v4.0.4 [Bugs URL](https://github.com/ElfFriend-DnD/foundryvtt-gmScreen/issues)
Health Estimate v30.8.7 [Bugs URL](https://github.com/mclemente/healthEstimate/issues)
Illandril's Token HUD scaler v2.2.1 [Bugs URL](https://github.com/illandril/FoundryVTT-token-hud-scale/issues)
Illandril's Token Tooltips v3.2.2 [Bugs URL](https://github.com/illandril/FoundryVTT-token-tooltips/issues)
Layer Hotkeys v2.4.1
lib - Color Settings v2.9.1
Forien's Copy Environment vv2.1.6 [Bugs URL](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-copy-environment/issues)
libWrapper v1.12.12.1 [Bugs URL](https://github.com/ruipin/fvtt-lib-wrapper/issues)
socketlib v1.0.13 [Bugs URL](https://github.com/manuelVo/foundryvtt-socketlib/issues)
Lock View v1.5.5
Module Management+ v2.2.0 [Bugs URL](https://github.com/mouse0270/module-credits/issues)
Monk's Combat Details v10.2 [Bugs URL](https://github.com/ironmonk88/monks-combat-details/issues)
Monk's Combat Marker v10.1 [Bugs URL](https://github.com/ironmonk88/monks-combat-marker/issues)
Monk's Little Details v10.09 [Bugs URL](https://github.com/ironmonk88/monks-little-details/issues)
Monk's Player Settings v10.1 [Bugs URL](https://github.com/ironmonk88/monks-player-settings/issues)
Monk's Scene Navigation v10.3 [Bugs URL](https://github.com/ironmonk88/monks-scene-navigation/issues)
Ownership Viewer v0.10.0 [Bugs URL](https://github.com/Malekal4699/fvtt-module-permission-viewer/issues)
PnP - Pointer and Pings! v2.4.1 [Bugs URL](https://github.com/Moerill/fvtt-pointer/issues)
Popout Resizer v1.4.5
Quick Insert - Search Widget v2.8.1 [Bugs URL](https://gitlab.com/fvtt-modules-lab/quick-insert/-/issues)
Splatter v3.2.2
Status Icon Counters v2.0.16 [Bugs URL](https://gitlab.com/woodentavern/status-icon-counters/-/issues)
Sync Token Names v1.0.4
Token Health v0.6.0
Token Mold v2.15.4 [Bugs URL](https://github.com/Moerill/token-mold/issues)
TouchVTT v1.9.1 [Bugs URL](https://github.com/Oromis/touch-vtt/issues)
Mobile Improvements v1.1.1 [Bugs URL](https://gitlab.com/fvtt-modules-lab/mobile-improvements/-/issues)
Minimal UI v1.5.6

**Comment by mouse0270** [comment]
Alright, So I downloaded and installed as many of these as I could, the ones I couldn't foundry said it couldn't install them or that it was for an older core version.

### System Details
**Browser:** Edge v1114.0.1823.37
**Foundry VTT:** v11.300
**System:** [Robert E. Howard's Conan: Adventures In An Age Undreamed Of](https://gitlab.com/fvtt-modiphius/foundryvtt-conan2d20) v1.9.3

### Active Modules
Bar Brawl v1.8.1 [Bugs URL](https://gitlab.com/woodentavern/foundryvtt-bar-brawl/-/issues)
Chat Portrait v0.7.4 [Bugs URL](https://github.com/ShoyuVanilla/FoundryVTT-Chat-Portrait/issues)
Combat Enhancements v1.2.2
Combat Tracker Effect Tooltips v11.0.0 [Bugs URL](https://github.com/dor-fvtt-released-modules/combat-tracker-effect-tooltips/issues)
Compendium Folders v2.6.1
Dice So Nice! v4.6.8 [Bugs URL](https://gitlab.com/riccisi/foundryvtt-dice-so-nice/-/issues)
Drag Ruler v1.13.4 [Bugs URL](https://github.com/manuelVo/foundryvtt-drag-ruler/issues)
Filepicker Improvements v1.2.5 [Bugs URL](https://github.com/manuel-hegner/foundry-filepicker-favorites/issues)
FXMaster v4.0.1 [Bugs URL](https://github.com/ghost-fvtt/fxmaster/issues)
GM Screen v4.0.4 [Bugs URL](https://github.com/ElfFriend-DnD/foundryvtt-gmScreen/issues)
Health Estimate v30.8.7 [Bugs URL](https://github.com/mclemente/healthEstimate/issues)
Illandril's Token HUD scaler v2.2.1 [Bugs URL](https://github.com/illandril/FoundryVTT-token-hud-scale/issues)
Illandril's Token Tooltips v3.2.2 [Bugs URL](https://github.com/illandril/FoundryVTT-token-tooltips/issues)
Layer Hotkeys v2.4.0
lib - Color Settings v2.9.1
Forien's Copy Environment vv2.1.6 [Bugs URL](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-copy-environment/issues)
libWrapper v1.12.12.1 [Bugs URL](https://github.com/ruipin/fvtt-lib-wrapper/issues)
socketlib v1.0.13 [Bugs URL](https://github.com/manuelVo/foundryvtt-socketlib/issues)
Lock View v1.5.5
Module Management+ v2.2.0 [Bugs URL](https://github.com/mouse0270/module-credits/issues)
Monk's Combat Details v10.2 [Bugs URL](https://github.com/ironmonk88/monks-combat-details/issues)
Monk's Combat Marker v10.1 [Bugs URL](https://github.com/ironmonk88/monks-combat-marker/issues)
Monk's Little Details v10.09 [Bugs URL](https://github.com/ironmonk88/monks-little-details/issues)
Monk's Player Settings v10.1 [Bugs URL](https://github.com/ironmonk88/monks-player-settings/issues)
Monk's Scene Navigation v10.3 [Bugs URL](https://github.com/ironmonk88/monks-scene-navigation/issues)
Quick Insert - Search Widget v2.8.3 [Bugs URL](https://gitlab.com/fvtt-modules-lab/quick-insert/-/issues)
Splatter v3.3
Status Icon Counters v2.0.17 [Bugs URL](https://gitlab.com/woodentavern/status-icon-counters/-/issues)

And everything seems to be working fine. The only other thing I can think to do is, if you go to https://github.com/mouse0270/module-credits/releases/tag/2.2.0 and download the `Source code
(zip)` file and extract those files over the module-credits folder in your Foundry User Data folder, it might be able to give us a better idea of which line is breaking, as `rollup.js` minifies the package for release.

**Comment by PanSatyricon** [comment]
Howdy!  First off, terrific module - thanks for your time and effort on developing it!  I was experiencing the same issue(s) as Valyar, attempted all of the usual things without any success, but took your advice on downloading the ZIP file.  Traced it to line 807 in module.mjs: _elemPackage.querySelector('.package-overview span.tag i.fas.fa-user').closest('span.tag').remove();_ which is consistently returning a null value instead of a valid object.

Commenting this out resolved the issue immediately (apparently the dislike is mutual between you and the author tag ;p); all other calls to FA icons are successful.  No other modules were active during this exercise and, with MM+ subsequently disabled completely, no instances of the fa-user icon appear in the default package list render.  Only other thing that might be common to both of us is...@r-valyar, any chance you're hosted through Forge?

Hope this helps!

**Comment by mouse0270** [comment]
No that completely makes sense, because I remove their author tag in favor of mine, as mine will list all available social networks that people may add, where there's just adds a link to the url from what I can tell. 

I can fix this today and push out an update later.

**Comment by r-valyar** [comment]
@PanSatyricon  I self-host in Azure

**Comment by PanSatyricon** [comment]
Heh - nice update title. ;)  Yes, everything appears to be functioning as expected with 2.2.1 both when loaded from the Forge bazaar and imported directly from source files.  Much appreciated!

**Comment by r-valyar** [comment]
I think there is an issue. On v11 the same world looks different when module is loaded:

V10: 
![image](https://github.com/mouse0270/module-credits/assets/63558984/ddb780b6-9f2d-49de-ab7c-c038dc479dcb)

V11:
![image](https://github.com/mouse0270/module-credits/assets/63558984/bbc17047-d823-438e-9539-14601dce5210)

**Comment by mouse0270** [comment]
> Heh - nice update title. ;) Yes, everything appears to be functioning as expected with 2.2.1 both when loaded from the Forge bazaar and imported directly from source files. Much appreciated!

I try to have fun with them... what the point of putting work into tracking all my changes if I can't? haha


@r-valyar are you getting any errors? It looks like something still isn't working as its supposed to.

**Comment by r-valyar** [comment]
@mouse0270  yep, this is the console output from V11 (on v10 all is clean)
![image](https://github.com/mouse0270/module-credits/assets/63558984/0a6abf9e-ec80-4dc8-8b38-12a8aacdc521)

**Comment by mouse0270** [comment]
Are you able to download and install the `Source Code (zip)` from https://github.com/mouse0270/module-credits/releases/tag/2.2.1 and see if it gives any better example of what the error might be.

**Comment by r-valyar** [comment]
![image](https://github.com/mouse0270/module-credits/assets/63558984/244df714-812e-49c3-aa7d-ce517ce4dd0e)

This is what I received after updating from the module interface. is the zip same?

**Comment by mouse0270** [comment]
Yeah, the "compatibility" warning is a dispute between foundry and I... Basically I wont mark it as v11 verified because I haven't went through every thing and tested everything, nor have I had anyone confirm everything work perfect, actually I've been told of bugs.

So its only verified to work on v10 because it works on v10... But foundry basically shows this warning unless you say its verified... but in my personal opinion, it hasn't been verified to work on v11.

As for the zip. The Package downloaded from the manifest.json url will downloaded a bundled version of the module that is minfiied. Overriding the files in module-credits with those found in Source Code (zip) will give you the unminified files and may make bug reporting easier to determine.

**Comment by r-valyar** [comment]
Yes, I get the verification part. No issue. Will get the zip tomorrow and test, as I am now on the tablet and can’t do much as I host machines in Azure.  I will be Guinea pig and see where we can go with this.

**Comment by mouse0270** [comment]
v2.2.1 seems to have fixed the issue for most others, so I am honestly not sure what is causing this specific issue. So any further details will help me fix the issue.

**Comment by r-valyar** [comment]
This is the console error that appears after I put the module from the zip file: 

![image](https://github.com/mouse0270/module-credits/assets/63558984/c5bff5d1-d89f-4f3e-a937-1e555256c4b0)

**Comment by mouse0270** [comment]
It says `bundle.min.mjs` are you sure you downloaded the file labeled `Source Code (zip)` and extracted its contents into the module-credits folder?

**Comment by r-valyar** [comment]
I just did. This is the output of the console from MS Edge: 
![image](https://github.com/mouse0270/module-credits/assets/63558984/1a277d5d-8fd7-401a-8434-7b1024c2eee8)

**Comment by mouse0270** [comment]
Can you do this again, but with the `Source Code (zip)` file here: https://github.com/mouse0270/module-credits/releases/tag/2.2.2.1

**Comment by r-valyar** [comment]
Absolutely! :)

Seems this fixed it: 
![image](https://github.com/mouse0270/module-credits/assets/63558984/a2a68bf3-10fc-4852-911f-f337acaeea27)

**Comment by mouse0270** [comment]
thanks for jumping through all those hoops for me, looks like I can close this issue and release v2.2.1.1
