### ISSUE TITLE
Error in console when opening Module Management

### ISSUE THREAD

**Issue by nschoenwald** [mouse0270/module-credits#103]
Using Chrome, foundry V10.291 and dnd5e 2.1.5, this error pops up when opening the Module Management:
<img width="621" alt="image" src="https://github.com/mouse0270/module-credits/assets/72390280/9731d25c-4a8c-40b9-9a0a-423adad7c539">

**Comment by Dyrnwyrm** [comment]
same error here, i needed to downgrade to the version before the v11 compatibility

**Comment by mouse0270** [comment]
This is most likely related to #101 which I hope to have the patch out tomorrow. I meant to get it today, but I was working on a new module and it went from 9am to 10pm in like 2 hours... No Idea where my Monday went

**Comment by mouse0270** [comment]
Can you confirm if version 2.2.1 fixes this https://github.com/mouse0270/module-credits/releases/tag/2.2.1
