### ISSUE TITLE
Foundry General Information changes with this installed

### ISSUE THREAD

**Issue by txm3278** [mouse0270/module-credits#106]
The general information section in the options tab inside a world loses some information when this module is installed.

Without Module Management+:
![image](https://github.com/mouse0270/module-credits/assets/25332081/07ff876f-650b-4bc7-96eb-cf7fd742f0c8)

With Module Management+:
![image](https://github.com/mouse0270/module-credits/assets/25332081/dc0f6162-1fe7-45ee-85f0-5eb83960b977)

**Comment by mouse0270** [comment]
Well It loses module count, the removing the name and placing the version of the system twice appears to be a bug

**Comment by mouse0270** [comment]
Should be fixed in version 2.2.1.2 https://github.com/mouse0270/module-credits/releases/tag/2.2.1.2

If not let me know.
