### ISSUE TITLE
Module dependencies not recognized on enabling/disabling modules?

### ISSUE THREAD

**Issue by coffiarts** [mouse0270/module-credits#107]
Is it only me? After enabling MM+ in Foundry 11, none of the module dependencies (be it required or recommended) seem to be recognized on enabling or disabling modules.

To be more precise: 

- disabling a mod that has dependencies will not trigger a warning prompt anymore whether you want to have dependencies deactivated as well
- likewise, enabling a mod that has dependencies will not trigger the prompt anymore that asks whether you want to have dependencies activated as well
- only socketlib as a dependency, as the most prominent example, still shows up when expanding the mod info. But I guess this is due to the additional "socket" declaration in module.json, or maybe it's generally handled explicitely?

Disabling MM+ brings back all those features at once.
I have no errors at all in my console apparently related to MM+

**Comment by mouse0270** [comment]
Are you talking about this Dialog? 
![image](https://github.com/mouse0270/module-credits/assets/564874/cffd2485-4621-432f-a5d8-4a7f495acb9c)

**Comment by coffiarts** [comment]
Yes, exactly. Meanwhile I've discovered that it seems to work at least for _some_ moduls, but I simply can't get what makes the difference.
For example...
- it does NOT work for this one: https://github.com/coffiarts/FoundryVTT-hot-pan/blob/latest/src/hot-pan/module.json
- and neither for this one: https://github.com/theripper93/Better-Roofs/blob/main/module.json

But it apparently DOES work here: https://github.com/otigon/automated-jb2a-animations/blob/main/module.json

Or here (just a snippet):
`  "relationships": {
    "requires": [
      {
        "id": "dsa5-core",
        "type": "module",
        "compatibility": {
          "minimum": "5.0.0"
        }
      }
    ],
    "systems": [
      {
        "id": "dsa5",
        "type": "system",
        "compatibility": {
          "minimum": "5.0.0"
        }
      }
    ]
  },
`
I can't understand what makes those module manifests behave differently in MM+

**Comment by mouse0270** [comment]
Can you do me a favor, can you disable everything but MM+. Then reload and just click on `Hot Pan & Zoom!` I think this is an issue with `recommends`. 

For example, if I disable Always Centred and Socketlib and then try enabling Hot Pan, I do get the dialog, but if Socketlib is already enabled but Always Centred is not, then I do not get the dialog.

So its a bug, but I want to make sure we have the same bug.

**Comment by coffiarts** [comment]
Thanks for your instant support! Really appreciate that :)
And yes, it's a good point to disable everything first. Find below my exact steps. I assume that they confirm your idea, but judge by yourself:

1.) Disable everything
![image](https://github.com/mouse0270/module-credits/assets/39616483/25eb1145-18b8-4137-b5a4-7a769f7d1961)

2.) Reload, then activate Hot Pa & Zoom! only
The prompt appears correctly, stating all the dependencies (including recommended):
![image](https://github.com/mouse0270/module-credits/assets/39616483/6b35c03c-4617-482b-b1e9-e0fe5d1a8da9)

3.) Reload, then activate MM+, confirming all the suggestions:
![image](https://github.com/mouse0270/module-credits/assets/39616483/23a96ee8-7dc0-4e96-ae5e-cbf9fec03fb7)
![image](https://github.com/mouse0270/module-credits/assets/39616483/b1b1b3ac-d055-4f3d-b4ca-86b1c8c99a03)
![image](https://github.com/mouse0270/module-credits/assets/39616483/78b56a14-6153-4e67-9079-6c4ac29cf798)

4.) Reload, then checking Hot Pan & Zoom! details
Only socketlib dependency is listed:
![image](https://github.com/mouse0270/module-credits/assets/39616483/f5528932-8357-45e3-a81c-da6be9e61e3a)

5.) Activate Hot Pan & Zoom!
This time nothing happens!
![image](https://github.com/mouse0270/module-credits/assets/39616483/1ddf5259-5523-439a-809d-414db6515ff4)

6.) DEactivate Hot Pan & Zoom!
Weirdly, now at least the prompt for socketlib is showing up!
But still not for the recommended one.
![image](https://github.com/mouse0270/module-credits/assets/39616483/924d3a62-cf0f-47d3-b7b8-ee41b5f86fa3)

Hope this helps. Really glad that you're looking into this.
AFAIK, the "recommended" flag has been recently introduced in Foundry 11.

**Comment by mouse0270** [comment]
Yeah, they choose recommends over optional, its a dispute between me and the devs. I disagree that recommends and optional are the same thing.

It does appear that my issue is what I think it is. So I will work on patching it. I already had a patch I forgot to update a week ago so maybe I can get it out today/tomorrow

**Comment by coffiarts** [comment]
Just a naive idea - given that it helps: Could we (aaaaaalll the mod authors out there) simply switch back to "optional" - at least as a workaround? Or is "optional" completely unsupported in v11?

**Comment by coffiarts** [comment]
And with your input I am seeing clearer... guess it's lines like this one that have to be changed, right?
https://github.com/mouse0270/module-credits/blob/74600d50a49d733fa87d2bd75058d209c6a75337/scripts/init.mjs#L108
I hope it's as simple as just replacing "optional" by "recommended"?
But I'll leave you to it, so that you can sort it out in peace and without any haste. Just curious ;-)

**Comment by mouse0270** [comment]
So basically, MM+ supports optional, and its supposed to support recommends, but I clearly missed something. haha.

My idea is this
**Recommends** Are modules that the author wants you to run alongside and that you should download and enable.
**Optional** Are modules that the author supports but wouldn't really recommend downloading and installing.

For example MM+ recommends that you install and use lib-wrapper and socketlib because these two modules improve the functionality of MM+. However, it has an optional module of libThemer which just adds support but I wouldn't want someone to download and install libThemer just because they installed MM+

**Comment by coffiarts** [comment]
Yeah, sounds like a plausible distinction.
Though I guess that 99% of the dependencies out there will match the "recommended" definition, while"optional" would be reserved for a very few things that authors just _have_ to support to make _some_ people happy, though it won't adding much value to their mods (never would have thought of that strict "optional" case myself).
In such a 1-%-optional scenario, the distinction might cause some confusion, as many people would mix up "optional" with "recommended", because they just don't care for the difference.

**Comment by mouse0270** [comment]
Honestly, its mostly the fact that I dislike the term "recommends" As it implies that I want you to install and run this module too. Where optional does not and simply implies that my module supports it.

So my supporting of recommends and optional is mostly because I disagree with the devs reasoning for "recommends" instead of optional.

**Comment by mouse0270** [comment]
Should be fixed in version 2.2.1.2 https://github.com/mouse0270/module-credits/releases/tag/2.2.1.2 

If not let me know.

**Comment by coffiarts** [comment]
Works absolutely fine now - everything as expected! Thanks for fixing that so rapidly.

Just a side note - it seems to me that the previous version was wrongly labelled as v2.2.2.1 instead of v2.2.1.1, that's why I wasn't able to run an auto-update in Foundry's setup.

To install the latest version, I had to do a complete uninstall and reinstall.

Before update:
![image](https://github.com/mouse0270/module-credits/assets/39616483/cfa34969-7c2b-4e17-ac21-bc9c527f1f05)

After uninstall and fresh install:
![image](https://github.com/mouse0270/module-credits/assets/39616483/02e205e0-3872-4898-b8fc-a31ed2f2f134)

**Comment by mouse0270** [comment]
Darn I was hoping fixing that on the admin portal would work... I might have to push a new update that is version 2.2.3 or something. Thanks for pointing this out to me.

**Comment by coffiarts** [comment]
Well, it was worth a try. I wouldn't be able myself to tell in advance how that "version syncing" really works in Foundry say. So it seems (from this example) that mod versions are locally stored and compared to the latest versions in the admin portal.
