### ISSUE TITLE
Insecure Request - Screenshot Attached

### ISSUE THREAD

**Issue by jocolamarco** [mouse0270/module-credits#11]
![imagem](https://user-images.githubusercontent.com/45291719/151808568-fb59b225-7366-4bb9-91c7-1aef30257c7f.png)

**Comment by mouse0270** [comment]
Do you know how to edit files? This is me being stupid. the url should be `//foundryvtt.mouse0270.com/module-credits/conflicts.json?time=${Date.now()}` but I screwed up in testing and put the `http:` at the start... I'd like to make sure that making that change resolves this before pushing out the update.

**Comment by jocolamarco** [comment]
Sure, let me know which file and line of code

**Comment by jocolamarco** [comment]
I did the EDIT you mentioned and I don't get the error message now.

I also get a new pop-up window:
![imagem](https://user-images.githubusercontent.com/45291719/151823253-1f874329-b672-480a-b698-7241ad8ad238.png)

**Comment by mouse0270** [comment]
Alright, that is the issue, I will include this in the next update. Hope you are enjoying the module.

**Comment by mouse0270** [comment]
Corrected in the latest release
