### ISSUE TITLE
The tag added for the bugs property has a title called "issues github" but not everybody uses GitHub

### ISSUE THREAD

**Issue by ghost91-** [mouse0270/module-credits#12]
Currently, when a manifest includes the `bugs` property, a tag with the title `"issues github"` is added. But not all modules use GitHub, so this should be adjusted to not be specific to GitHub. It's only the title text, the links works correctly when clicked.

**Comment by mouse0270** [comment]
I can easily fix the title, I don't need to include that text and it can just read `issues`. But you do make a valid point about not everyone using Github, making the icon a little hard to use. (I have corrected this so the title no longer reads `issues github` and instead just reads `issues`)

For example I could replace it with the `bug` icon, but then people using `Bug Reporter` will see the same icon twice. I guess I'll have to see if I can find another icon that works will for bugs/issues.

**Comment by mouse0270** [comment]
I am really not a fan of either of those... what about help? 
![image](https://user-images.githubusercontent.com/564874/152001872-abf12417-a725-435c-b0a3-91dede6f48f1.png)

**Comment by ghost91-** [comment]
Hm, I don't really like the question mark, personally. I guess if both GitHub and Gitlab can't come up with a good icon, it's a hard problem to solve :D

I actually like the github icon better than the question mark. If you want to get fancy, you could check if either "github" or "gitlab" is part of the url, and if that is the case, use the corresponding icon. If not, use the github icon as fallback. You can also bring bitbucket into the mix if you want. That still doesn't cover every case, in particular not self hosted instances of GitLab or Gitea, but it's good enough, I think.

**Comment by mouse0270** [comment]
I am going to leave this open until I am happy with an icon. Cause you are right, github isn't perfect, but it does get the point across for now. I think I can figure out something better if I think on it for a bit.

**Comment by mouse0270** [comment]
This has been fixed with localization options
