### ISSUE TITLE
Correctly render relative URLs in markdown files

### ISSUE THREAD

**Issue by ghost91-** [mouse0270/module-credits#13]
Currently, relative URLs in markdown files (README, CHANGELOG, etc.) are rendered as if they were relative to the base URL of foundry. Instead, they should be rendered relative to the markdown file, so that they work correctly (images show up etc.).

**Comment by mouse0270** [comment]
I might just be being dumb, I am not sure how I can solve this. I am not sure I can set a divs relative path?

relative URLs will also have issues for example, people who use relative paths for images on there readme/changelog files on sites like github/gitlab, but then don't package that folder with there module, even if I was able to figure out how to make a div load files relative to a path, I'd still be unable to load these paths as they simply don't exist in any relative directory.

**Comment by ghost91-** [comment]
Of course it only works when the files are bundled, that's a given. I would expect the `baseUrl` option of Marked to solve this issue (see https://marked.js.org/using_advanced#options).

**Comment by mouse0270** [comment]
OMG I am stupid... When I tested this, I used `baseUrl : '/modules/${MODULEID}` and it never worked as I expected it to... I just went and played around with it... It needs to be `baseUrl : '/modules/${MODULEID}/`

That trailing slash is what I was missing. this wont fix everything. For example, imaged not packed into the module or if the file uses `/assets/image.png` It appears `baseUrl` ignores paths that starts with `/`

This functionality is added and will in in the next release... Its at least a step forward, still not perfect, but getting there.

**Comment by ghost91-** [comment]
yeah, I think that's a good compromise. If people use absolute URLs, it's their own fault. They really shouldn't (I think that also breaks on GitHub / GitLab). And if they don't bundle their files but use relative urls, they also cannot expect it to work.

**Comment by mouse0270** [comment]
I could do something a little hacky, I could replace all instances of `](/` with `[(` which would basically remove that slash, and then parse the markdown via `marked.js`

**Comment by ghost91-** [comment]
Yeah, that’s a tough problem. Though I would argue that it’s worth creating issues at the authors' repositories if you notice something is not conformant with how foundry core expects it. Personally, I wouldn’t go so far as to parse the `author` tag for example. People should just do it correctly 😅

**Comment by mouse0270** [comment]
Included in 1.1.0. Released
