### ISSUE TITLE
Expand settings search to include settings title and description in addition to mod title

### ISSUE THREAD

**Issue by dmrickey** [mouse0270/module-credits#19]
DF Settings Clarity has (had..it's currently broken in v9) a really nice search function in the settings page that also searched the name of individual settings plus their descriptions. Even if it's fixed, I'd rather only have one search bar on my settings page, so if that's something you could include, that'd be awesome.

**Comment by mouse0270** [comment]
Um, I never used that module, I don't see why I cant include it. I will add it to the todo list, this is a good feature to have.

**Comment by dmrickey** [comment]
Its best hair is that it adds an icon next to each setting so you (as the gm) can tell which settings are world settings vs which settings are individual client settings

**Comment by mouse0270** [comment]
The icons are added to v2 of MM+ however the search is not. I am closing this as I do not plan to add a search with foundry's new settings layout.
