### ISSUE TITLE
Modules conflicting with with MC formating

### ISSUE THREAD

**Issue by Weissrolf** [mouse0270/module-credits#20]
Hello. Here are some module I found conflicting with the latest MC formatting changes:

Quick Module Enable: Causes bottom buttons of Manage Modules window to drop off the screen in big mode (no problem with Settings window) and adds a large empty area below those buttons in normal mode.

Window Controls: Causes the Configure Settings -> Module Settings to not make full use of the window height (window larger than content) in normal mode. No problem in big mode.

SocketSettings: Not so much a conflict, but a fix. MC in big mode fixes SocketSettings causing two scroll-bars (window size) in normal mode.

**Comment by mouse0270** [comment]
**Quick Module Enable** Alright, well those are really big words and completely throws off the UI. I wonder if instead of trying to set my heights via css I need to just use javascript. Its not as efficient but it'll prevent more of these conflicts... Also I might just patch this module, cause it makes the screen ugly either way.

**Window Controls** I am not sure what you are describing here? If you can, please provide a screenshot.

**SocketSettings** Are you saying I fix this with my module, or this needs fixed by my module? It appears my module makes the window work a little nicer with socketsettings enabled. However I'd like to make the settings button more consistent and fix issues when you enable the Options in SocketSettings

**Comment by Weissrolf** [comment]
**Windows Controls** conflict in normal mode (not Big Picture mode):
![image](https://user-images.githubusercontent.com/22069354/152647924-69617e9d-c1fc-4b68-a529-7320ed52d643.png)

**SocketSettings**: I am saying that MC fixed the SocketSettings issue when Big Picture mode is used, because then the window size is fixed (and usually enlarged). I posted an issue with SocketSettings, because it is their issue, but MC kind of works around it.

The scroll-bar happens, because SocketSettings causes the Core Settings window to originally not scale properly big. Once you click another tab and back (like Module Settings and then back to System Settings) it's fixed by the window being resized.

When Big Picture mode is not used then fixed windows might be the way to go, others may have more insight on that, though. Only the System Settings (PF2) are few enough to not need the full height of the screen in my world, so dynamic sizes would do little for them, unless a maximum size is set (maybe 3/4 or 2/3 screen height max?).

**Comment by mouse0270** [comment]
Can you provide you provide me with a list of modules you are using, I am not sure its windows controls causing that issue for you?
![image](https://user-images.githubusercontent.com/564874/152648542-22542b4f-1076-484c-8b8e-e6482e15863e.png)

Oh yeah, I kinda just setting the default height of that window to 75% of the screen height. I think this will fix that additional scrollbar for not only my module, but many others that adjust those screens. Basically foundry takes the height of the window before `renderSettingsConfig`, so any module that uses that hook and adds stuff breaks foundry's expected height. By giving the scrollable area a defined height, foundry wont auto adjusts the height of this window as much, but it does mean your stuck with a window that may have lots of blank space... I personally would like to have the blank space then the additional scrollbar.

**Comment by Weissrolf** [comment]
You need to expand the settings to see the window content being cut off in height.
![image](https://user-images.githubusercontent.com/22069354/152658786-d1c4aa6b-7ce0-4877-a89e-8dc9c0162fb0.png)

**Comment by mouse0270** [comment]
What system are you using? It might be the issue.

**Comment by Weissrolf** [comment]
I am using PF2E, but I see the same in a newly created DnD5E world. Firefox with extensions or Chrome without.

You might be using too large a zoom (including Chrome by default using Windows DPI settings to zoom in even at 100%)? The lower the browser zoom the more it becomes apparent.

30%:
![image](https://user-images.githubusercontent.com/22069354/152662094-b711c203-8ace-4682-8b47-87f9c37f5430.png)

170%:
![image](https://user-images.githubusercontent.com/22069354/152662200-ea5eb8cb-983f-4fa8-ad38-26120d7d8042.png)

**Comment by mouse0270** [comment]
I for the life of me can not replicate this one, I'd be happy to hope into a discord call and you can share your screen if you are okay with that... But I am at a loss otherwise.

**Comment by mouse0270** [comment]
Most of these should be resolved with the exception of Quick Module Enable, which I do have a plan to resolve in the next release

**Comment by bnp800** [comment]
For Window control, here's the same issue with screenshot 
https://github.com/saif-ellafi/foundryvtt-window-controls/issues/17

**Comment by mouse0270** [comment]
Does this exists when using version 1.1.7+?

**Comment by mouse0270** [comment]
No update on this in a long time. Assuming its been resolved
