### ISSUE TITLE
Feature: Only show conflicts of active modules

### ISSUE THREAD

**Issue by Weissrolf** [mouse0270/module-credits#21]
Hello.

Wouldn't it make sense to only display conflicts for active modules instead of installed ones? Once a conflicting module is deactivated there is no more conflict, so I would prefer if MC would not display one anymore then.

**Comment by mouse0270** [comment]
# Version 1.1.7 - A little More Subtle
- Changed the notify conflicts logic on the Manage Modules button, to only show a conflict number related to active conflicts not all conflicts.

Next release

**Comment by mouse0270** [comment]
In the current release
