### ISSUE TITLE
Feature Request: More compact Game Settings sidebar tab

### ISSUE THREAD

**Issue by esheyw** [mouse0270/module-credits#22]
The last thing TidyUI did for me that your module doesn't yet: remove the blank space between buttons on the settings tab, and change the aspect ratio a bit.

Without TidyUI: https://i.imgur.com/uZePCvQ.png

With TidyUI: https://i.imgur.com/P33kbdr.png

I just like the latter aesthetically a lot. Toggleable option maybe? Please? Love everything else about MM+, thanks.

**Comment by mouse0270** [comment]
If I do do this, it will be a similar design to my libThemer implemtation of TidyUI. Ignore the colors thats part of the modules design, but this is my take on Cleaner Settings menu.

![image](https://user-images.githubusercontent.com/564874/152689663-7e4e850a-b58d-40cf-9b14-45451847a5bd.png)

**Comment by esheyw** [comment]
That's well within what I was hoping for. Looks a lot cleaner than gaps everywhere IMO.

**Comment by MrVauxs** [comment]
Any progress on this? This may very well be the last thing that holds people away from going from Tidy UI to MM+

**Comment by mouse0270** [comment]
> Any progress on this? This may very well be the last thing that holds people away from going from Tidy UI to MM+

Yes and no. This isn't technically a part of this module, sadly it will be a part of my `libThemer` module which is almost done. But that module lets you modify CSS variables or toggle custom stylesheets on the fly. Here is a quick Preview showing off my Tidy Side Bar Stylesheet, and Custom Fonts working from Google Fonts API.

https://streamable.com/oqhndk

I need to fix some small issues and finish localizing the nearly 200 CSS variables you can modify

**Comment by mouse0270** [comment]
[libThemer](https://github.com/mouse0270/lib-themer/releases/tag/1.0.0) is awaiting approval and seems to be taking some time, but it can be found [here](https://github.com/mouse0270/lib-themer/releases/tag/1.0.0) and will allow you to customize the look of Foundry.

I am closing as this will not be implemented within this module as its out of the scope of this module. Please use [libThemer](https://github.com/mouse0270/lib-themer/releases/tag/1.0.0) or let me know of another alternative.

**Comment by mouse0270** [comment]
Update After the longest wait for a module approval over 27 hours in waiting, it just got approved: https://foundryvtt.com/packages/lib-themer
