### ISSUE TITLE
Bug: changelogs not marking viewed under certain circumstances

### ISSUE THREAD

**Issue by esheyw** [mouse0270/module-credits#24]
If you have a module that has a changelog you haven't marked viewed, and you uninstall said module before you get around to it, it gets stuck: https://gfycat.com/OddConsiderateHorsefly 

That gif is from a pf2e world, and as you can see there's a starwarsffg module in there; I do have that module installed still, and that's an error on its dev's end, but also maybe an edge case you want to account for, because after recording the above, I loaded the appropriate world, and it worked correctly: https://i.imgur.com/JCvKe74.png

edit: so I was wrong, that star wars module does have its' settings correct, and wasn't showing on the list in the pf2e world. So that's probably less uncommon than I was thinking, and would happen any time a module for another system than the one your current world is has updated.

edit2: a 'reset changelogs' does remove the old entries, so that's working fine, and after the reset it didn't show the star wars module in the pf2e world, but did correctly show it on going back to the star wars world. I'm vaguely remembering that module may have updated its manifest link recently? that could have broken something?

**Comment by mouse0270** [comment]
I will add a check when updating changelogs that I loop through the previously tracked changelogs and remove any that don't exist or no longer have a file in their directory.

**Comment by mouse0270** [comment]
This should be resolved in the latest update, if not please re-open this issue
