### ISSUE TITLE
getSystemFiles.find is not a method

### ISSUE THREAD

**Issue by dmrickey** [mouse0270/module-credits#25]
I'm getting this on startup on one of my player clients (probably clients, as well, but I was logging in here to verify something)

![image](https://user-images.githubusercontent.com/3664822/153957100-4ccb5ef4-57dd-407b-b336-aa6dcce88340.png)

`find` is an array method, looking at `checkIfFileExists` it looks to be returning `false`, or possibly a file or an array of files.

Putting a breakpoint there, for me it's currently returning `false` so `false.find(...)` is blowing up.

**Comment by mouse0270** [comment]
Whoops there is supposed to be an if before that that only continues if it isn't false. I will push out a patch later tonight/tomorrow morning. Thank you for making me aware of this

**Comment by mouse0270** [comment]
This should be resolved in the latest update, if not please re-open this issue
