### ISSUE TITLE
[System Conflict] The Settings Menu of the System DSA/TDE 5 is broken

### ISSUE THREAD

**Issue by vt-tom** [mouse0270/module-credits#27]
If i use MM+ with the System Das Schwarze Auge/The Dark Eye (5th Edition) the Settings aren't scrollable if they are to long for the Window:

Game Settings:
![grafik](https://user-images.githubusercontent.com/80099175/154628046-a9d4e6ce-eed5-4563-8250-3cac6af97018.png)

Module Settings:
![grafik](https://user-images.githubusercontent.com/80099175/154628206-3c50ca50-341e-424f-8a68-e24f87f518b0.png)

**Comment by mouse0270** [comment]
Though this is technically the fault of the system for changing how scrolling works on these windows I will write a patch for it, to make it work similar to the default foundry system. I'll restore the default system scrolling options if this system is being used alongside MM+ which should resolve the issue.

I'll try to have the patch out today.

**Comment by mouse0270** [comment]
Its actually already fixed, I just need to comment out some stuff before I can push the patch as I was getting ready to release a big update this weekend. So It'll be out soon.
