### ISSUE TITLE
"This is not a registered game setting" error

### ISSUE THREAD

**Issue by SecretSquirrel77** [mouse0270/module-credits#28]
Foundry v9, dnd5e, latest patch. 
I get this error in the console when module management + is active. Doesn't seem to matter what other modules I have active (except libwrapper).
![Capture](https://user-images.githubusercontent.com/77705375/154860597-acc075fe-09ab-4aa4-a179-45866d53d386.PNG)

**Comment by mouse0270** [comment]
Please try with the latest version just published, if the issue still exists, let me know.
