### ISSUE TITLE
Still a small issue with mm+ and DSA/TDE

### ISSUE THREAD

**Issue by vt-tom** [mouse0270/module-credits#29]
Sorry, but i have still an issue with mm+ and TDE/DSA (5th). Now the scrollbar works, but at the bottom of the menu is a blank space. ist this an issue which you can solve or is this system related and i have to open a ticket in the system github.

![grafik](https://user-images.githubusercontent.com/80099175/155089199-70d5053b-1321-4ef7-a03d-3ea5b92519c1.png)

**Comment by mouse0270** [comment]
Forgot to check big picture mode...

I will have a patch out later today.

**Comment by vt-tom** [comment]
You are great, thanks 👍

**Comment by mouse0270** [comment]
Moving all issues related to settings and Big Picture Mode to issue #32
