### ISSUE TITLE
New Tag for Wiki (Documentation URL if provided or Readme.md)

### ISSUE THREAD

**Issue by apoapostolov** [mouse0270/module-credits#3]
Small buttonw ith new color next to version, text "Wiki" and links to either documentation URL in manifest, or readme.md

However, readme.md is usually what is shown on the github main page of a project, so maybe readme.md is not that much useful.

**Comment by mouse0270** [comment]
Tags for Wiki, Issues and Changelog has been included in version v0.0.2

Also added the ability to display local `changelog.md` files within foundry.
