### ISSUE TITLE
Feature request: 'Default to Module Settings Tab' option

### ISSUE THREAD

**Issue by Doresain** [mouse0270/module-credits#30]
Hey man, great module. Have switched to using it instead of Tidy UI - Game Settings, but I'm missing the Tidy UI option to have the settings menu always default to the 'Module Settings' tab. If you could provide similar functionality here that would be killer.

Thanks again!

**Comment by esheyw** [comment]
I'm also missing this. In a similar vein, a hotkey to open directly to module settings might be nice?

**Comment by mouse0270** [comment]
Great suggestion, I will look into adding this into an update soon.

**Comment by mouse0270** [comment]
The new settings window in v10 makes this interface less needed. Also, the module management window now includes a button to open that module's specific settings.

I am going to consider this closed for now. If you have a more specific request, please re-open this issue or create a new one.
