### ISSUE TITLE
Remove colors and backgrounds from module.css

### ISSUE THREAD

**Issue by NutritiousCookie** [mouse0270/module-credits#31]
Setting the background color and image conflicts with UI modules. The one I'm concerned with is [5e Dark Mode](https://github.com/Stryxin/dnd5edark-foundryvtt).

![image](https://user-images.githubusercontent.com/30578022/156942321-88bcc4bf-4f40-47ca-92e0-3da8df2244b0.png)
![image](https://user-images.githubusercontent.com/30578022/156942390-ccf0b978-c75e-46f5-82bb-f61d6dedb86c.png)

**Comment by mouse0270** [comment]
MM+ v2+ has much more streamlined css. This should no longer be an issue. If it still is please re-open this issue.
