### ISSUE TITLE
Brazilian Portuguese Localization

### ISSUE THREAD

**Issue by MagelaCE** [mouse0270/module-credits#33]
Here the JSON file with pt-BBR localization strings.
[pt-BR.zip](https://github.com/mouse0270/module-credits/files/8303163/pt-BR.zip)

Please include preset strings in localization

**Comment by mouse0270** [comment]
I will see what I can do to include this in v2. However the strings are not exactly the same.

**Comment by mouse0270** [comment]
Sorry thank you for taking the time to do this. I finally sat down today and localized everything, but given the major format change alot of this isn't lined up more. I am going to close this, but if you decided you want to update this for version 2.1.1. Please let me know.
