### ISSUE TITLE
Module Conflict with DF Settings Clarity

### ISSUE THREAD

**Issue by Brimcon** [mouse0270/module-credits#34]
Re-posting from https://github.com/flamewave000/dragonflagon-fvtt/issues/345 as I'm not sure which module is the cause of the issue.
**Module**
DF Settings Clarity 3.2.1
Module Management+ 1.1.11
Foundry 9.255

**Describe the issue**
With DF Settings Clarity enabled, typing anything in the "Search for a Setting" bar makes every description fill every setting of a module.

**To Reproduce**
1. Enable both DF Settings Clarity and Module Management+
2. Go to Module Settings in Configure Settings
3. Type in anything in the "Start typing to search for a setting"
4. Observe Error by opening up a setting Dropdown

**Expected behavior**
Settings screen remains as before with the highlight as normal.

**Screenshots (Optional)**
Before: 
![image](https://user-images.githubusercontent.com/7198283/159413136-68309908-ac06-4fac-a1b8-c0f886aabae7.png)

After
![image](https://user-images.githubusercontent.com/7198283/159412793-b0903712-d12c-489a-883a-bf16ddfc1302.png)

**Comment by mouse0270** [comment]
MM+ v2+ includes icons to inform the user if a setting is `client` or `world` scope...

If updating to v2 I'd suggest using either my module or DF Settings Clarity
