### ISSUE TITLE
Bug: There's something going on with conditionally-viewable non-gm settings. I think.

### ISSUE THREAD

**Issue by esheyw** [mouse0270/module-credits#35]
So, in some combinations of modules, this happens to Drag Ruler settings (but only on non-gm players): https://i.imgur.com/zpBXM71.png 

As you can see, the bottom setting gets cut off a bit? And if I disable pathfinding as an option for players: https://i.imgur.com/jPeIidx.png then that setting gets cut off instead.

This isn't a Drag Ruler issue thought, it seems to be when a combination of it and any of several other modules are active? I'm currently investigating.

**Comment by esheyw** [comment]
List of modules that when active, trigger this bug:

**Comment by esheyw** [comment]
Modules that produce the bug WITH player pathfinding allowed:

Dice So Nice!

**Comment by esheyw** [comment]
Okay I'm gonna stop testing here because I think I figured it out: if expanding the Drag Ruler section would create a scrollbar, the bug is invoked. So it's not a matter of which modules are active, just if enough that register settings are active at once.

**Comment by esheyw** [comment]
Okay so I forgot a variable to test, and on further investigation, it's not a player-side bug, it's a foundry-on-firefox bug. the scrollbar is very different on FF vs chrome.

**Comment by mouse0270** [comment]
This should be resolved with v2 on Foundry v10
