### ISSUE TITLE
PF2e System Settings not fully visible -> Empty Space misleading

### ISSUE THREAD

**Issue by jocolamarco** [mouse0270/module-credits#36]
![image](https://user-images.githubusercontent.com/45291719/161431568-6e997dc2-39d0-4e70-875e-296039a8418b.png)

completely missed these settings as they were hidden:
![image](https://user-images.githubusercontent.com/45291719/161431583-b8c18dd6-f192-4803-89e9-94c6ec1ad95f.png)

**Comment by Truncated** [comment]
Same on PF1e

**Comment by mouse0270** [comment]
Does this still happen on the new versions? I don't think v2 of MM+ does `Big Picture Mode` on settings yet.

**Comment by mouse0270** [comment]
Closing this as its a part of issue #32
