### ISSUE TITLE
Wall Height breaks credits

### ISSUE THREAD

**Issue by dmrickey** [mouse0270/module-credits#39]
Every time I join my world I'm greeted with the following
![image](https://user-images.githubusercontent.com/3664822/168379411-fa1a146c-205e-409a-82d6-e048835c7d78.png)

**Comment by mouse0270** [comment]
Interesting. I will look into this, its odd as I use that module.

Sorry for the impossible long delay, I work 4 jobs over the summer months and my free time dies off.

**Comment by mouse0270** [comment]
I am going to close this. It appears newer version of wall height no longer include or link to these files so this issue isn't something I can replicate. If you are still getting this issue after v2 of MM+ for Foundry v10 please reopen this issue and let me know the versions of everything you are running.
