### ISSUE TITLE
More Settings for better customization

### ISSUE THREAD

**Issue by apoapostolov** [mouse0270/module-credits#4]
- [x] Option to hide JavaScript and CSS tags that are not really useful to most users and are non-interactive
- [ ] #5

**Comment by mouse0270** [comment]
It's funny you asked.. the next version adds icons and allows you to condense the tags to only show icons yo allow for more space. Should be out today or tomorrow

**Comment by mouse0270** [comment]
Yeah here is what it looks like with all of the `condense` options turned on
![image](https://user-images.githubusercontent.com/564874/127748167-c33f93bc-3379-4ba0-9776-e93325e27f3c.png)

**Comment by mouse0270** [comment]
Included in version 0.0.3... Author tags seperated into own issue
