### ISSUE TITLE
Stuck on loading game - foundryvtt.mouse0270.com

### ISSUE THREAD

**Issue by bsleys** [mouse0270/module-credits#43]
It's not 100% consistent but about 50% of the time while having module-credit active the table top stops loading and at the bottom of the browser it states it looking for foundryvtt.mouse0270.com.  I did I text search though all my modules and that string only show in this module and after disabling it the problem goes away.

Bob

**Comment by mouse0270** [comment]
I will take a look at this. I assume it is my server rejecting the connection. I think you should be able to turn of global conflicts and if not I will have to add that.

Sorry for the impossible long delay, I work 4 jobs over the summer months and my free time dies off.

**Comment by mouse0270** [comment]
Removed global conflicts in v2.0.0+

Will be adding this feature back in the future when I have more time to get it working better
