### ISSUE TITLE
Allow saving current selected values to an existing profile without changing them

### ISSUE THREAD

**Issue by Truncated** [mouse0270/module-credits#46]
Due to these logic points, a user cannot save the current selections to an existing preset without first selecting the preset and, thereby, erasing all of the changes and requiring the modules to be unselected / selected again.

- The Preset field always opens empty with "Select a Preset..."
- The Save key on this default selection is greyed out.
- Any Preset selected always applies the values immediately.
- You must select a preset first before you can save updates / changes to it.
- Names of Presets can be duplicated and will not update existing Presets.

**_To streamline this logic and user experience, please consider the following enhancement:_**
Allow the Save Preset button to be active when Select a Preset... is the value. When clicked, an eval presents one of two options:

1. IF no Presets exist, message error shows to "Create a new preset first" and + button (Create new Preset) on top left is highlighted (pulse the current hover state a few times).
2. IF Presets exist, pop-up "Select existing Preset to update with current values" with dropdown of Preset options. Choice in dropdown + "Save Update" button resolves the action.

**Usibility thoughts:**
- First considered suggested greying out the save button if no Presets existed instead of the message. That feels "refined", and nicer for power users who may be messing with modules all the time (devs, content creators, etc.). but I thought that consistent behavior and an educating message would be better for new / infrequent users of this, which I believe are the vast majority of GMs and Players, who may only muck about in this when testing after updates or when they want to swap out modules that cover different elements, maybe every few months to a year.
- A simple binary toggle on the interface to set behavior of Presets (auto apply or select only) seemed like a decent idea, after thinking it through it seemed liked trading one thing to remember to click for another.

**Comment by mouse0270** [comment]
Try v2.0.0 and let me know how you like I handle presets. It should feel a lot nicer now. If not please open this issue again.
