### ISSUE TITLE
v10 compatibility?

### ISSUE THREAD

**Issue by ctbritt** [mouse0270/module-credits#47]
When activated, the module prevents using Configure Settings. Window opens, but no settings are available. Have checked with no other modules active.

**Comment by mouse0270** [comment]
The module is not compatible with v10 yet. I have it mostly rewritten and ready for an update should be out by the end of the long weekend.

**Comment by mouse0270** [comment]
Module has been updated to support v10.

Small bugs such as localization and old setting left in will be patched out in v2.0.1
