### ISSUE TITLE
[Feature] Locked settings are hidden from players 

### ISSUE THREAD

**Issue by Moses148** [mouse0270/module-credits#49]
Whilst locking settings is great, it would be nice if there was a setting that hides all locked settings from players so that the settings page isn't bogged down.

**Comment by mouse0270** [comment]
Let me think about this, clearly, it wouldn't be hard to implement. However I am not sure how I feel about removing things. Locking settings is meant to prevent users from changing a value, but they can still see the value and what it is set to.

Hiding it means the user never even knows the value exists. If I did implement a setting like this, it may not be in a way many would like. For example, I'd add a client setting that can't be locked or synced to that would allow clients to hide or show locked settings.

this way if a player wanted to hide these settings to clear up there settings window they could, but a Game Master could never forcible hide them from the players view.

Or maybe I'll just hide them, I have to think more about this before determining a path I'd like to go down. Maybe if I get more feedback.

**Comment by MrVauxs** [comment]
I think a toggle hiding and unhiding unchangeable settings would be a better solution. The default could be set in Module Management's settings.

**Comment by Moses148** [comment]
I'm sorry if I made myself unclear, this is what a meant. A setting that the GM can enable that hides the locked settings from players if the GM so desires, and if the GM doesn't mind the players seeing them then they can have it disabled. Alot of my modules my players don't know what they do nor will they understand what the settings for them are, so the option to hide the irrelevant settings (locked ones) so that only the ones they can see are the ones they can change. I feel my players are more likely to sit through and take their time with the settings if all they see are 20 odd settings, rather than 120 with 100 of them locked.

**Comment by mouse0270** [comment]
I've decided in my next release where I plan on focusing on locking/forcing/syncing settings, I will add a setting that will allow Game Masters to hide locked settings.

**Comment by Moses148** [comment]
Awesome. Any idea when this release will release? (No pressure, just curious)

**Comment by mouse0270** [comment]
Hopefully today, as I have to push out a patch related to locking settings.

**Comment by Moses148** [comment]
That's great to hear, keep up the good work :D

**Comment by mouse0270** [comment]
If you wouldn't mind testing out [Version 2.0.4](https://github.com/mouse0270/module-credits/releases/tag/2.0.4) and letting me know if this is an acceptable solution. Please keep in mind of the following known issues

- Known Issue: Because of the way I hide settings, there is a small flash for players when opening the settings window
- Known Issue: The setting counter does not update when settings are hidden from player.

manifest.json: https://github.com/mouse0270/module-credits/releases/download/2.0.4/module.json

**Comment by MrVauxs** [comment]
Everything works lovely.

**Comment by MrVauxs** [comment]
Won't make a new issue about it though, you have a typo
![image](https://user-images.githubusercontent.com/32039708/191297569-e3715f2c-e036-465c-9a1b-6118afeb948b.png)

**Comment by mouse0270** [comment]
Thanks for the catch. Please keep in mind, that when I push the update live to foundry it will still be using version 2.0.4. I've fixed this and hiding the sync button when a setting is locked. So you may need to uninstall and reinstall later to get all of those small fixes.
