### ISSUE TITLE
Option to hide Developer Credit to avoid broken, lengthy tags.

### ISSUE THREAD

**Issue by mouse0270** [mouse0270/module-credits#5]

**Comment by mouse0270** [comment]
At this time I do not plan on hiding authors names/links. It was one of the major purposes of this project.

I may look into an option that helps minimize the impact of modules that have many authors and/or modules where the author imporperly formated their module.js files.

**Comment by xdy** [comment]
Maybe have a setting that only shows a credits icon, with a hover of the names?
Would be useful for modules with plenty of authors/authors with long names as that makes the line overflow (Token Magic FX or most League modules for example).
Or, trigger this if the combined length of the authors is too long. (Whatever 'too long' means, perhaps simply if it would overflow one line?)

**Comment by mouse0270** [comment]
The plan right now is to limit author name to set number of characters and then just cut then off and add ...

As for token fx magic I think if you have more then x authors it's going to collapse then into a single tag you can expand and close.
