### ISSUE TITLE
2.0.2 Fails to Stylize Module Management

### ISSUE THREAD

**Issue by MrVauxs** [mouse0270/module-credits#51]
![image](https://user-images.githubusercontent.com/32039708/191145743-a641d10a-47b9-4369-a4f4-cfc7c368e2a3.png)

**Comment by mouse0270** [comment]
Are you able to add and test a line of code for me? I think I know what the issue is

**Comment by mouse0270** [comment]
Can you install the module via this manifest and let me know if the issue is fixed?
https://github.com/mouse0270/module-credits/releases/download/2.0.3/module.json

**Comment by MrVauxs** [comment]
Will do

**Comment by MrVauxs** [comment]
It's fixed

**Comment by mouse0270** [comment]
What appears to have happened is one of those modules is saying it requires a module you do not have installed and I forgot to check that. So its trying to get the title of a module you don't have installed. lol

**Comment by MrVauxs** [comment]
Yeah it's a common occurrence between V9 and V10 updates. Updates sometimes don't bring up dependencies, or the dependency is deemed an error by V10 by not having a script it says it has or similar.
