### ISSUE TITLE
Permanent migrating...

### ISSUE THREAD

**Issue by infias** [mouse0270/module-credits#54]
It never finishes and throws a console error and comes back each time.
![image](https://user-images.githubusercontent.com/88762169/191358379-d691deef-b7a9-4ca9-b744-09b3b460e501.png)
![image](https://user-images.githubusercontent.com/88762169/191358456-742409f7-8591-4297-b166-5128f67c1c6c.png)

**Comment by mouse0270** [comment]
Would you mind installing MM+ via this manifest and letting me know if the issue is resolved: https://github.com/mouse0270/module-credits/releases/download/2.0.5/module.json

**Comment by mouse0270** [comment]
This should be fixed in 2.0.5, if not, reopen this issue
