### ISSUE TITLE
Feature Request: Rolling automatic 'previous' preset

### ISSUE THREAD

**Issue by esheyw** [mouse0270/module-credits#55]
So I think the best way this would work is:
- on opening the MM window, take a snapshot of enabled modules
- on 'save modules' (from the actual button only), (over)write the list to a `Previous` preset (name negotiable)
- don't overwrite Previous with the current snapshot if loading a preset

This would be nice QoL for total scatterbrains like me who forget to update their 'testing' presets as they go, but would like to go back just one set of enabled modules, when the list of what those were no longer exists in active memory 😅You can just open MM, open presets, hit 'Previous', it's like ctrl-z for MM.

**Comment by mouse0270** [comment]
OMG I WOULD LOVE THIS... SO MANY TIMES I ENABLE LIKE 10 MODULES AND SOMETHING FREAKS OUT AND I JUST WANT TO GO BACK

TOTALLY ADDING THIS!!!

**Comment by mouse0270** [comment]
![image](https://user-images.githubusercontent.com/564874/191992741-e5f3aeb6-b4ae-46dd-9496-27b7ad5a2f77.png)

Just a quick update as there is still some bugs with it... But this will let you go back 5 states by default, but can be set to a number between 0 and 10, where 0 is infinite... However that might cause some bloat, so it would be suggested not to use it.

**Comment by mouse0270** [comment]
Included in v2.1.0
