### ISSUE TITLE
Hiding active module count as default?

### ISSUE THREAD

**Issue by Oshcakes** [mouse0270/module-credits#66]
What is the reason this is done? I see you include a link to the systems read me in place of the active module count. That little section there gives a lot of information from a support perspective, ie sometimes users think they have disabled all modules when they actually have not.

**Comment by mouse0270** [comment]
Oh cause I meant to move that number down to the manage modules button and forgot...
![image](https://user-images.githubusercontent.com/564874/192854591-5ac93580-0d8b-42cd-9175-5175ae7455fa.png)

**Comment by Oshcakes** [comment]
Cool, that will work.

**Comment by tjlanza** [comment]
This strikes me as a change for change's sake, rather than a functional improvement. The number of inactive modules is not often relevant information. Module count would be better left presented as core.

**Comment by mouse0270** [comment]
Version 2.1.6 Now has a setting to choose where to display active module count, it is hidden by default. As this is the way I want to use my module, this will be the default setting, however, your now able to enable it for how you would like it.
