### ISSUE TITLE
DevTools warning at the browser console

### ISSUE THREAD

**Issue by paulohdsc** [mouse0270/module-credits#7]
This is a really small issue, but I thought it was worth letting you know that DevTools is throwing a warning at the console about failing to load one of the module's files.

![chrome_FI9tCam7K5](https://user-images.githubusercontent.com/75817094/134098446-d69304ba-b7c4-44c9-81b1-f916605e4095.jpg)

**Comment by mouse0270** [comment]
this file has been included in the latest release and should no longer throw this warning.
