### ISSUE TITLE
Bug: Cannot read properties of undefined (reading 'replaceAll')

### ISSUE THREAD

**Issue by Doresain** [mouse0270/module-credits#70]
Hey, simple one that breaks processing of modules to add buttons etc on loading the module list: 

![image](https://user-images.githubusercontent.com/26096062/193127908-537bfee8-20f1-4316-9e78-d5a9580d0fd2.png)

Looks like there's a chance `conflict.reason` might be empty? For me it always breaks between Active effect manager and Chat Commands:
![image](https://user-images.githubusercontent.com/26096062/193128078-a9b2b652-c9bc-425b-86e2-65ad796c8624.png)

**Comment by mouse0270** [comment]
Interesting, I will install those two modules and check it out. Its probably easy enough fix for me to get out with todays update later.

**Comment by mouse0270** [comment]
Yup, reason was not defined, I included a patch, it wont crash anymore, but it will says `REASON WAS NOT LISTED`

**Comment by mouse0270** [comment]
Should be resolved in v2.1.5

**Comment by Doresain** [comment]
Confirmed fixed with the update, thanks man!
