### ISSUE TITLE
[Bug] Pin Cushion Entry links to wrong repository

### ISSUE THREAD

**Issue by SirMotte** [mouse0270/module-credits#80]
The Pin Cushion extension seems to be linked to the wrong Repository. The browser is forwarded to the "[Variant Encumbrance](https://github.com/p4535992/foundryvtt-variant-encumbrance-dnd5e)".

The correct link would be [this](https://github.com/p4535992/foundryvtt-pin-cushion).

**Comment by mouse0270** [comment]
This is an error in Pin Cushions Module.json file, MM+ just links to the urls provided, so if a developer has the wrong link there, it will link to the wrong location.

https://github.com/p4535992/foundryvtt-pin-cushion/blob/master/src/module.json#L123

**Comment by SirMotte** [comment]
Gotcha, I was unsure how you fetch the details. I'll contact the author, thanks!

**Comment by mouse0270** [comment]
No worries, not the first module to make that mistake. Its easy to miss. lol
