### ISSUE TITLE
[Bug] Configuration Settings window content not scaled properly in WFRP4e

### ISSUE THREAD

**Issue by Berytak** [mouse0270/module-credits#81]
The content in the Configuration Settings Window is not scaled properly in a WFRP4e game. The content has the original size with a scroll button, but the Window itself is large as it should be.

![image](https://user-images.githubusercontent.com/85394657/194945797-c130d645-1454-4def-ad75-5dc588433a97.png)

I'm having this issue on all three tabs, Core Settings, System Settings and Module Settings.

**Comment by mouse0270** [comment]
I really don't mean this in a harsh or bad way, but I don't plan on fixing or supporting v9. I spent a lot of time updating the module for v10.

I'd suggest not using big-picture mode in v9 to avoid this issue. You might be able to fix this using might be able to fix this yourself using the module Custom CSS.

**Comment by Berytak** [comment]
Absolutely understandable and comprehensible, so not an issue for me.
Unfortunately, v10 will have to wait a little longer, as I have D&D modules that have not yet been updated. But if my issue is fixed in v10, I will gladly wait.
