### ISSUE TITLE
Locked settings are not checked to still exist when saving after closing

### ISSUE THREAD

**Issue by PepijnMC** [mouse0270/module-credits#89]
The following code, particularly line 1187 returns an error when a previously locked setting no longer exists in the module as `settingDetails` is `undefined`. 
https://github.com/mouse0270/module-credits/blob/e0d3dc35e5c6f609a21af2886b2465ef66f15cba/scripts/module.mjs#L1183-L1194

Changing it to something like this seems to resolve the issue:
```js
if (settingDetails) MMP.#LockedSettings[`${key}`] = game.settings.get(settingDetails.namespace, settingDetails.key);
else delete MMP.#LockedSettings[`${key}`];
```

**Comment by mouse0270** [comment]
This has been added in version 2.1.6. thanks!!!
