### ISSUE TITLE
Conflict with DF Chat Enhancements

### ISSUE THREAD

**Issue by flamewave000** [mouse0270/module-credits#9]
A user reported this conflict here: [DF Chat Enhancements: Module Credits #298](https://github.com/flamewave000/dragonflagon-fvtt/issues/298).

It appears we are both using the `marked` library, but maybe different versions. Mine uses the `marked.parse()` function to convert markdown to HTML, while yours appears to use `marked()` instead.

I just want to reach out and see if we can resolve this some way that works best. I was kind of thinking that since Markdown is a very popular format, maybe a Library Module would make sense, similar to arcanist's [Ace Library](https://github.com/arcanistzed/acelib).

**Comment by mouse0270** [comment]
I am actually updating module credits to use esmodule instead, which should solve this conflict as my version of marked wont be used outside of my module. At least that is my understanding.

**Comment by mouse0270** [comment]
Just confirmed, in the next release of module credits our mods do not conflict. However, if you do want to expand marked into a library, we can go from there.

**Comment by mouse0270** [comment]
Resolved in version 0.0.4.0 (I don't fully understand ES Modules, but if I understand them correctly, this should no longer cause a conflict.)

**Comment by flamewave000** [comment]
Sounds good. I think a library module would be good too though so users only need to download one copy of Marked instead of two.

Esmodules essentially "scope" your code so that they can only access things in the `globalThis` and what ever is directly imported, and nothing outside a module can see inside it. So any regular script running in the window cannot see anything defined inside a module.
