### ISSUE TITLE
Bug: Clicking a module expand button saves settings and prompts for reload

### ISSUE THREAD

**Issue by esheyw** [mouse0270/module-credits#95]
If I open MM, check a currently disabled module's checkbox, and then try and expand any module's info, the current list gets saved and I get the reload prompt: 
![](https://i.imgur.com/VntCWVY.gif)

**Comment by mouse0270** [comment]
Whoops looks like I forgot `event.preventDefault`

**Comment by mouse0270** [comment]
Should be resolved in v2.2.0+ If not please re-open or create a new issue
