### ISSUE TITLE
Lot's of missing features?

### ISSUE THREAD

**Issue by XiaoKe89** [mouse0270/module-credits#99]
So I just installed this module and I'm a bit perplexed as a lot of the features don't seem to be showing up/working for me. 

1. None of the extra buttons that show the module author, website, link to open settings, etc show on the module management page.
2. I'm not seeing any conflicts but I'm not sure if that's because there are none or if it's just not showing.
3. I'm only able to rename or lock the first module in the list
4.  The spreadsheet button is missing from the module management screen even after enabling it in the settings
5. With libthemer installed and the alternative checkbox option activated, the green check doesn't show and all the modules show blank making it impossible to know which are active and which are inactive without using the filter at the top

I used find the culprit and deactivated everything except Module Management+ (And find the culprit) and all of these issues still persist so it doesn't seem to be a conflict with any other mod.
I'm on Foundry core 10.291 and Module Management+ 2.1.6 and I've tested it on both PF2E 4.12.6 and DND5e 2.2.1

I'm not sure if this is user error or if it's the mod, I've fiddled with the settings and I can't seem to figure out why a lot of the features aren't working so any help would be much appreciated!

**Comment by mouse0270** [comment]
I haven't seen this complaint yet; I can take a look at it when I have a moment.

**Comment by mouse0270** [comment]
Can you confirm if v2.2.1 fixes this issue for you?

**Comment by mouse0270** [comment]
Assuming this is resolved as it appears to be resolved for most other people

**Comment by XiaoKe89** [comment]
Hey sorry, for the late reply. I just tested with 2.2.1 and it's still not working.

**Comment by XiaoKe89** [comment]
OK so new update. I tried doing a find the culprit again and this time it sort of worked. So with only module management+ and find the culprit it shows the buttons, I can rename/lock modules, and the checkbox works but only on the first 35 modules in my list any after that exhibit the same issue I first reported.

In addition to that There seem to be some conflicts with other modules when I activate them they shrink the number of modules that have the extra features provided by module management+, I'll list the conflicts below:

[Advanced Macros](https://github.com/mclemente/fvtt-advanced-macros) - With this one enabled no modules have the extra features
[PF2E Animations ](https://github.com/MrVauxs/pf2e-jb2a-macros) - With this one enabled only the first module in the list has the extra features
[Bing Bong ](https://github.com/Gawdl3y/foundry-bing-bong) - With this one enabled only the first 2 modules have the extra features
[Break Time](https://github.com/ironmonk88/breaktime) - With this one enabled only the first 3 modules have the extra features
[Combat Ready](https://github.com/Teshynil/combatready) - With this one enabled only the first 4 modules have the extra features
[Compendium Folders ](https://github.com/earlSt1/vtt-compendium-folders) - With this one enabled only the first 5 modules have the extra features
[DF Chat Enhancements](https://github.com/flamewave000/dragonflagon-fvtt/tree/master/df-chat-enhance) - With this one enabled only the first 8 modules have the extra features
[DF Manual Rolls](https://github.com/flamewave000/dragonflagon-fvtt/tree/master/df-manual-rolls) - With this one enabled only the first 9 modules have the extra features
[DFreds Droppables](https://github.com/DFreds/dfreds-droppables) - With this one enabled only the first 10 modules have the extra features
[DF User Logger ](https://github.com/flamewave000/dragonflagon-fvtt/tree/master/df-logger) - With this one enabled only the first 11 modules have the extra features
[Dice So nice](https://gitlab.com/riccisi/foundryvtt-dice-so-nice) - With this one enabled only the first 12 modules have the extra features
[Dice Tray](https://gitlab.com/asacolips-projects/foundry-mods/foundry-vtt-dice-calculator) - With this one enabled only the first 19 modules have the extra features
[Foriens Quest Log](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-quest-log) - With this one enabled only the first 21 modules have the extra features
[Health Estimate](https://github.com/mclemente/healthEstimate) - With this one enabled only the first 23 modules have the extra features
[JB2A ](https://github.com/Jules-Bens-Aa/JB2A_DnD5e) - With this one enabled only the first 24 modules have the extra features
[Chat Commander (Library for DF Chat Enhancements)](https://gitlab.com/woodentavern/foundryvtt-chat-command-lib) - With this one enabled only the first 25 modules have the extra features
[Color Settings Lib (Library for several mods)](https://github.com/ardittristan/VTTColorSettings) - With this one enabled only the first 26 modules have the extra features
[Lib themer](https://github.com/mouse0270/lib-themer) - With this one enabled only the first 29 modules have the extra features
[Libwrapper (Library for multiple mods) ](https://github.com/ruipin/fvtt-lib-wrapper) - With this one enabled only the first 30 modules have the extra features
[Token Action Hud PF2e](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e) - With this one enabled only the first 32 modules have the extra features
[Lock View ](https://github.com/CDeenen/LockView) - With this one enabled only the first 33 modules have the extra features
[Material Deck](https://github.com/CDeenen/MaterialDeck) - With this one enabled only the first 34 modules have the extra features

Regardless of modules enabled or disabled I'm still not seeing any conflicts (Though I'm unsure of where those normally show up if any)
And also redardless of what modules are enabled or disabled the google sheet doesn't show when the option is marked in settings.

I'm not sure what is causing these weird incompatibilities is there like a limit in the mod that it only works on a certain number of modules? That's the only reason I could see for why it only works on the first 35.
As for all the mod incompatibilities I understand that's a lot and especially if no one else is having issues so if I'm just SOL then oh well but I still thought it important to make you aware of.
This is after updating the module to 2.2.1 BTW

**Comment by mouse0270** [comment]
Are you using version 2.2.1.1 or 2.2.1?

**Comment by XiaoKe89** [comment]
2.2.2.1. I just updated it yesterday. Before the update nothing was showing even with all modules disabled other than module management+ and find the culprit

**Comment by mouse0270** [comment]
Wait so does v2.2.1.1 work or not?

**Comment by XiaoKe89** [comment]
Sorry if I wasn't clear 2.2.1.1 does not work. It exhibts the behavior I detailed in the comment above

**Comment by mouse0270** [comment]
Can you please Download `Source Code (zip)` from https://github.com/mouse0270/module-credits/releases/tag/2.2.2.1 and extract these files and replace the content inside of `module-credits` folder in your foundry UserData? 

After doing this, you may need to restart your foundry instance and then start up the world. Once in the world please hit F12 and report any errors in your consol.

I really don't know whats going wrong and need more details.

**Comment by XiaoKe89** [comment]
Ok, I downloaded the files and replaced all the files, and restarted the server.
I opened up the console and then opened the manage modules menu, the error persists  and it gives this error:

"module.mjs:776 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'Configure')
[Detected 1 package: module-credits]
    at Object.renderModuleManagement [as fn] (module.mjs:776:160)"

**Comment by mouse0270** [comment]
Looks like I messed up and did `game.i18n.translations.SETTINGS.Configure` instead of `game.i18n.localize('SETTINGS.Configure')` I suspect your foundry is not set to English as its default language?

This should be easy enough to fix, I will patch it tomorrow and see if I did this anywhere else and fix that too.

**Comment by XiaoKe89** [comment]
Ohhhhh that makes sense. I'm using a mod to edit the CSS of the login screen which changes the language to Latin to do so, everything shows in English but the language is set to Latin to change the CSS.

**Comment by mouse0270** [comment]
Well to be fair, you're language setting isn't the problem... This is my screw up, but if the reason you were getting this issue is because of this mistake of mine. I'll get it patched tomorrow.

**Comment by XiaoKe89** [comment]
Ok sounds great! Glad we got it figured out!

**Comment by mouse0270** [comment]
Should be fixed in version 2.2.1.2 https://github.com/mouse0270/module-credits/releases/tag/2.2.1.2

If not let me know.
